### ISSUE TITLE
`String::replace` buggy in certain cases

### ISSUE THREAD

**Issue by rspierce** [arduino/ArduinoCore-API#240] opened 2024-11-30 08:01 UTC
### Description

replacing multiple occurrences of a string with a smaller string only works for an odd number of occurrences

#### Boards platform name

["**Raspberry Pi Pico/RP2040**" boards platform](https://arduino-pico.readthedocs.io/en/latest/) from [Earle F. Philhower, III](https://github.com/earlephilhower)

##### Original report

Not specified

#### Last verified with

4.0.3

### Code demonstrating problem

```cpp
void setup() {
  Serial.begin(9600);
  while (!Serial) {}
  // this code should remove all occurrences of "narf" from the string
  String s = "narf";
  Serial.println();
  Serial.print("input: (");
  Serial.print(s);
  Serial.println(")");
  s.replace("narf", "");
  Serial.print("result: (");
  Serial.print(s);
  Serial.println(")");

  s = "narf narf";
  Serial.println();
  Serial.print("input: (");
  Serial.print(s);
  Serial.println(")");
  s.replace("narf", "");
  Serial.print("result: (");
  Serial.print(s);
  Serial.println(")");
}

void loop() {}
```

Serial monitor output:

```text
input: (narf)
result: ()

input: (narf narf)
result: (narf narf)
```

### Additional information

In this code:

https://github.com/earlephilhower/ArduinoCore-API/blob/ece6e68f29c6f406a4434659bcbcfe558baaa3a9/api/String.cpp#L667-L671

```cpp
		while ((foundAt = strstr(readFrom, find.buffer)) != NULL) {
			readFrom = foundAt + find.len;
			diff = 0 - diff;
			size -= diff;
		}
```

line 669 (`diff = 0 - diff;`) should be above the `while` loop.

**Comment by per1234** [comment] 2024-11-30 08:56
Closing as duplicate of https://github.com/arduino/ArduinoCore-API/issues/199, which has already been fixed by https://github.com/arduino/ArduinoCore-API/pull/200.

@rspierce the reason you are still affected by https://github.com/arduino/ArduinoCore-API/issues/199 is because [the bug fix](https://github.com/arduino/ArduinoCore-API/pull/200) was made after the version of `arduino/ArduinoCore-API` that is in use by the ["Raspberry Pi Pico/RP2040" boards platform](https://arduino-pico.readthedocs.io/en/latest/). You can submit a request for the platform to update its version of `arduino/ArduinoCore-API` by submitting an issue to the tracker in that repository:

https://github.com/earlephilhower/arduino-pico/issues

**Closed by per1234** 2024-11-30 08:56 UTC
Labels: bug
